name: ai_one_flutter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  provider: ^6.1.5
  dio: ^5.3.0
  gif_view: ^1.0.3
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.3
  mailto: ^2.0.0
  # url_launcher: ^6.2.2
  
  carousel_slider: ^5.1.1
  local_auth: ^2.1.8 # Ensure this is present if using biometric auth
  url_launcher: ^6.2.4
 

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ # <--- C'est la seule ligne nécessaire pour inclure tout le contenu de ce dossier